name: Trigger RDP workflows of Second github account

on:
  push:
    branches:
      - main  # You can change this to any branch you want

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/tajbir6/Gmail-RDP/actions/workflows/rdp.yml/dispatches
